#get the directory of this makefile
AMRLIB:=$(TEMPCLAW)/amrclaw/src/2d
#TEMPGEOLIB2D:=$(TEMPCLAW)/geoclaw/src/2d/shallow


#list of common sources for amr 2d codes
COMMON_MODULES += \
 $(AMRLIB)/amr_module.f90 \
 $(AMRLIB)/regions_module.f90 \
 $(AMRLIB)/adjoint_module.f90

#list of common sources needed for geoclaw codes (subset of amr dependencies)
COMMON_MODULES += \
 $(TEMPGEOLIB2D)/utility_module.f90 \
 $(TEMPGEOLIB2D)/geoclaw_module.f90 \
 $(TEMPGEOLIB2D)/topo_module.f90 \
 $(TEMPGEOLIB2D)/qinit_module.f90 \
 $(TEMPGEOLIB2D)/refinement_module.f90 \
 $(TEMPGEOLIB2D)/fgout_module.f90 \
 $(TEMPGEOLIB2D)/fgmax_module.f90 \
 $(TEMPGEOLIB2D)/surge/model_storm_module.f90 \
 $(TEMPGEOLIB2D)/surge/data_storm_module.f90 \
 $(TEMPGEOLIB2D)/surge/storm_module.f90 \
 $(TEMPGEOLIB2D)/gauges_module.f90 \
 $(TEMPGEOLIB2D)/multilayer/multilayer_module.f90 \
 $(TEMPGEOLIB2D)/friction_module.f90 \
 $(TEMPGEOLIB2D)/adjointsup_module.f90 \
 $(TEMPBOUSSLIB2D)/bouss_module.f90  \
 $(TEMPBOUSSLIB2D)/bouss_regions_module.f90 \

# list of source files from AMR library. 
COMMON_SOURCES += \
  $(AMRLIB)/prefilp.f90 \
  $(AMRLIB)/trimbd.f90 \
  $(TEMPBOUSSLIB2D)/bound.f90 \
  $(AMRLIB)/intfil.f90 \
  $(AMRLIB)/flagregions2.f90  \
  $(AMRLIB)/quick_sort1.f \
  $(AMRLIB)/quick_sort_reals.f \
  $(AMRLIB)/estdt.f \
  $(AMRLIB)/check4nans.f90 \
  $(AMRLIB)/init_iflags.f \
  $(AMRLIB)/igetsp.f \
  $(AMRLIB)/reclam.f \
  $(AMRLIB)/birect.f \
  $(AMRLIB)/cleanup.f \
  $(AMRLIB)/colate2.f \
  $(AMRLIB)/bufnst2.f \
  $(AMRLIB)/flagger.f \
  $(AMRLIB)/fixcapaq.f \
  $(AMRLIB)/flglvl2.f \
  $(AMRLIB)/fluxad.f \
  $(AMRLIB)/fluxsv.f \
  $(AMRLIB)/grdfit2.f \
  $(AMRLIB)/moment.f90 \
  $(AMRLIB)/nestck2.f \
  $(AMRLIB)/prepc.f \
  $(AMRLIB)/prepf.f \
  $(AMRLIB)/projec2.f \
  $(AMRLIB)/signs.f \
  $(AMRLIB)/findcut.f \
  $(AMRLIB)/smartbis.f \
  $(AMRLIB)/putnod.f \
  $(AMRLIB)/putsp.f \
  $(AMRLIB)/regrid.f \
  $(AMRLIB)/setuse.f \
  $(AMRLIB)/stst1.f \
  $(AMRLIB)/nodget.f \
  $(AMRLIB)/basic.f \
  $(AMRLIB)/outval.f \
  $(AMRLIB)/copysol.f \
  $(AMRLIB)/outvar.f \
  $(AMRLIB)/outmsh.f \
  $(AMRLIB)/outtre.f \
  $(AMRLIB)/domain.f  \
  $(AMRLIB)/cellave.f \
  $(AMRLIB)/fdisc.f \
  $(AMRLIB)/fss.f \
  $(AMRLIB)/zeroin.f \
  $(AMRLIB)/setflags.f \
  $(AMRLIB)/shiftset2.f \
  $(AMRLIB)/conck.f \
  $(AMRLIB)/domshrink.f \
  $(AMRLIB)/domprep.f \
  $(AMRLIB)/domup.f \
  $(AMRLIB)/domcopy.f \
  $(AMRLIB)/setdomflags.f \
  $(AMRLIB)/setIndices.f \
  $(AMRLIB)/coarseGridFlagSet.f \
  $(AMRLIB)/addflags.f \
  $(AMRLIB)/baseCheck.f \
  $(AMRLIB)/drivesort.f \
  $(AMRLIB)/flagcheck.f \
  $(AMRLIB)/domgrid.f \
  $(AMRLIB)/setPhysBndryFlags.f \
  $(AMRLIB)/griddomup.f \
  $(AMRLIB)/griddomcopy.f \
  $(AMRLIB)/griddomshrink.f \
  $(AMRLIB)/intcopy.f \
  $(AMRLIB)/preintcopy.f \
  $(AMRLIB)/icall.f \
  $(AMRLIB)/preicall.f \
  $(AMRLIB)/inlinelimiter.f \
  $(AMRLIB)/cstore.f \
  $(AMRLIB)/saveqc.f \
  $(AMRLIB)/opendatafile.f \
  $(AMRLIB)/init_bndryList.f \
  $(AMRLIB)/resize_bndryList.f \
  $(AMRLIB)/init_nodes.f90 \
  $(AMRLIB)/restrt_nodes.f90 \
  $(AMRLIB)/resize_nodes.f90 \
  $(AMRLIB)/init_alloc.f90 \
  $(AMRLIB)/restrt_alloc.f90 \
  $(AMRLIB)/resize_alloc.f90

# list of source files from GEOCLAW library. 
COMMON_SOURCES += \
  $(TEMPGEOLIB2D)/setprob.f90 \
  $(TEMPBOUSSLIB2D)/qinit.f90 \
  $(TEMPGEOLIB2D)/topo_update.f90 \
  $(TEMPGEOLIB2D)/cellgridintegrate2.f \
  $(TEMPGEOLIB2D)/topointegral.f \
  $(TEMPGEOLIB2D)/bilinearintegral.f \
  $(TEMPGEOLIB2D)/stepgrid.f \
  $(TEMPBOUSSLIB2D)/src2.f90 \
  $(TEMPBOUSSLIB2D)/src1d.f90 \
  $(TEMPGEOLIB2D)/step2.f90 \
  $(TEMPGEOLIB2D)/flux2fw.f \
  $(TEMPGEOLIB2D)/qad.f \
  $(TEMPBOUSSLIB2D)/valout.f90 \
  $(TEMPBOUSSLIB2D)/filval.f90 \
  $(TEMPGEOLIB2D)/filpatch.f90 \
  $(TEMPGEOLIB2D)/bc2amr.f90 \
  $(TEMPBOUSSLIB2D)/update.f90 \
  $(TEMPBOUSSLIB2D)/setaux.f90 \
  $(TEMPGEOLIB2D)/flag2refine2.f90  \
  $(TEMPBOUSSLIB2D)/b4step2.f90 \
  $(TEMPGEOLIB2D)/upbnd.f  \
  $(TEMPBOUSSLIB2D)/tick.f \
  $(TEMPGEOLIB2D)/setgrd.f \
  $(TEMPGEOLIB2D)/gfixup.f \
  $(TEMPGEOLIB2D)/ginit.f \
  $(TEMPBOUSSLIB2D)/getmaxspeed.f90 \
  $(TEMPBOUSSLIB2D)/advanc.f \
  $(TEMPBOUSSLIB2D)/amr2.f90 \
  $(TEMPGEOLIB2D)/fgmax_read.f90 \
  $(TEMPGEOLIB2D)/fgmax_frompatch.f90 \
  $(TEMPGEOLIB2D)/fgmax_interp.f90 \
  $(TEMPGEOLIB2D)/fgmax_values.f90 \
  $(TEMPGEOLIB2D)/fgmax_finalize.f90 \
  $(TEMPGEOLIB2D)/check.f \
  $(TEMPGEOLIB2D)/restrt.f \
  $(TEMPGEOLIB2D)/errest.f \
  $(TEMPGEOLIB2D)/errf1.f \
  $(TEMPGEOLIB2D)/coarsen.f \
  $(TEMPGEOLIB2D)/auxcoarsen.f \
  $(TEMPGEOLIB2D)/prepbigstep.f \
  $(TEMPGEOLIB2D)/prepregstep.f \
  $(TEMPGEOLIB2D)/set_eta_init.f90 \
  $(TEMPBOUSSLIB2D)/geoclaw_riemann_utils.f \
  $(TEMPBOUSSLIB2D)/rpn2_hyper_bouss_geoclaw.f90 \
  $(TEMPBOUSSLIB2D)/rpt2_hyper_bouss_geoclaw.f90  \
  

